//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CoffeeDBEntities1 : DbContext
{
    public CoffeeDBEntities1()
        : base("name=CoffeeDBEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<AddToCart> AddToCarts { get; set; }
    public DbSet<Admin> Admins { get; set; }
    public DbSet<Bank> Banks { get; set; }
    public DbSet<Customer> Customers { get; set; }
    public DbSet<Item> Items { get; set; }
    public DbSet<Order> Orders { get; set; }
    public DbSet<PackageItem> PackageItems { get; set; }
    public DbSet<Package> Packages { get; set; }
    public DbSet<Payment> Payments { get; set; }
    public DbSet<PIVirtual> PIVirtuals { get; set; }
    public DbSet<ServiceTeam> ServiceTeams { get; set; }
}
