//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AddToCart
{
    public int Id { get; set; }
    public string packageID { get; set; }
    public string itemID { get; set; }
    public string orderID { get; set; }
    public string paymentID { get; set; }
    public string sessionID { get; set; }
    public int Qty { get; set; }
}

public partial class Admin
{
    public int adminID { get; set; }
    public string adminName { get; set; }
    public string adminEmail { get; set; }
    public string adminPassword { get; set; }
}

public partial class Bank
{
    public int bankID { get; set; }
    public string cardNumber { get; set; }
    public string amount { get; set; }
    public string bankName { get; set; }
}

public partial class Customer
{
    public Customer()
    {
        this.Orders = new HashSet<Order>();
    }

    public int customerID { get; set; }
    public string customerName { get; set; }
    public string customerNRC { get; set; }
    public decimal customerPhone { get; set; }
    public string customerAddress { get; set; }
    public string customerEmail { get; set; }
    public int customerStatus { get; set; }
    public string customerPassword { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Item
{
    public Item()
    {
        this.PackageItems = new HashSet<PackageItem>();
    }

    public int itemID { get; set; }
    public string itemName { get; set; }
    public string itemCategory { get; set; }
    public byte[] itemImage { get; set; }
    public int itemQuantity { get; set; }
    public int itemPrice { get; set; }

    public virtual ICollection<PackageItem> PackageItems { get; set; }
}

public partial class Order
{
    public Order()
    {
        this.Payments = new HashSet<Payment>();
    }

    public int orderID { get; set; }
    public System.DateTime orderDate { get; set; }
    public int orderStatus { get; set; }
    public string deliveryAddress { get; set; }
    public int Package_packageID { get; set; }
    public int Customer_customerID { get; set; }
    public int ServiceTeam_serviceID { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual ICollection<Payment> Payments { get; set; }
    public virtual Package Package { get; set; }
    public virtual ServiceTeam ServiceTeam { get; set; }
}

public partial class Package
{
    public Package()
    {
        this.Orders = new HashSet<Order>();
        this.PackageItems = new HashSet<PackageItem>();
    }

    public int packageID { get; set; }
    public string packageName { get; set; }
    public string packageType { get; set; }
    public byte[] packageImage { get; set; }
    public int packageStatus { get; set; }
    public int packageCount { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
    public virtual ICollection<PackageItem> PackageItems { get; set; }
}

public partial class PackageItem
{
    public int Id { get; set; }
    public int Package_packageID { get; set; }
    public int Item_itemID { get; set; }

    public virtual Item Item { get; set; }
    public virtual Package Package { get; set; }
}

public partial class Payment
{
    public int id { get; set; }
    public int paymentID { get; set; }
    public int unitPrice { get; set; }
    public decimal amount { get; set; }
    public decimal totalPrice { get; set; }
    public int itemID { get; set; }
    public int Order_orderID { get; set; }

    public virtual Order Order { get; set; }
}

public partial class PIVirtual
{
    public int Id { get; set; }
    public Nullable<int> packageID { get; set; }
    public Nullable<int> itemID { get; set; }
    public string sessionID { get; set; }
}

public partial class ServiceTeam
{
    public ServiceTeam()
    {
        this.Orders = new HashSet<Order>();
    }

    public int serviceID { get; set; }
    public string serviceName { get; set; }
    public string servicePassword { get; set; }
    public string serviceEmail { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
}
